# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DA_tydX9ZySVcuOtswXubFbbo3Eye_I0
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8m.pt")

results = model.train(data="/content/drive/MyDrive/Plants Diseases Detection and Classification.v12i.yolov8/data.yaml",epochs=50,lr0=0.0005,augment=True)